[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16

; Bumped to handle massive Laravel vendor directories
opcache.max_accelerated_files=32769 

; 0 in production so it never checks for file changes (Maximum speed)
opcache.validate_timestamps=0 

; Must be 1 for Laravel/PHP attributes and reflection to work
opcache.save_comments=1