FROM nginx:alpine

# Copy PROD Nginx configuration
COPY docker/nginx/default.prod.conf /etc/nginx/conf.d/default.conf

# We only need the public directory for Nginx to serve static assets
COPY ./public /var/www/public